CREATE DOMAIN NAME_TYPE AS VARCHAR(255);
CREATE DOMAIN LOCATION_TYPE AS VARCHAR(255);
CREATE DOMAIN EMAIL_TYPE AS VARCHAR(50);
CREATE DOMAIN PHONE_NB_TYPE AS VARCHAR(15);


CREATE TABLE Building (
	Bldg_Name NAME_TYPE NOT NULL PRIMARY KEY,
	Nb_Rooms INT NOT NULL,
	Bldg_Type VARCHAR(100) NOT NULL,
	Bldg_Maint_Repair_Status VARCHAR(100) NOT NULL,
	Bldg_Maint_Sched_Date DATE NOT NULL,
	Bldg_Last_Maintained DATE
);

CREATE TABLE Employee (
	Empl_ID INT NOT NULL PRIMARY KEY,
	Empl_Name NAME_TYPE,
	Email_Address EMAIL_TYPE NOT NULL UNIQUE,
	Empl_Phone_Nb PHONE_NB_TYPE NOT NULL UNIQUE,
	Empl_Position VARCHAR(100) NOT NULL,
	Salary INT NOT NULL,
	Manager_ID INT NOT NULL
);

CREATE TYPE TIME_INTERVAL AS (
	Start_Time TIME,
	End_Time TIME
);

CREATE TABLE Amenities (
	Amenity_ID INT NOT NULL PRIMARY KEY,
	Amenity_Type VARCHAR(100),
	Amenity_Location LOCATION_TYPE NOT NULL,
	Wkdy_Hrs TIME_INTERVAL,
	Wknd_Hrs TIME_INTERVAL
);

